name: "Build & Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: false

      - name: Build
        run: |
          go build -v ./...
          go vet ./...

      - name: Test
        run: go test -v ./...
